packages/runtime-core/apiCreateApp.ts
=> feat: App.use

README.md, packages/runtime-core/apiCreateApp.ts, packages/runtime-core/apiInject.ts, packages/runtime-core/component.ts, packages/runtime-core/index.ts, packages/runtime-core/renderer.ts, packages/runtime-core/vnode.ts
=> Feat provide inject

README.md, example/chibi-vue_store/index.html, example/chibi-vue_store/package.json, example/chibi-vue_store/pnpm-lock.yaml, example/chibi-vue_store/src/App.vue, example/chibi-vue_store/src/main.ts, example/chibi-vue_store/src/store/count.store.ts, example/chibi-vue_store/vite.config.js, package.json, packages/@extensions/chibi-vue-store/createStore.ts, packages/@extensions/chibi-vue-store/index.ts, packages/@extensions/chibi-vue-store/rootStore.ts, packages/@extensions/chibi-vue-store/store.ts, packages/runtime-core/component.ts, packages/runtime-core/index.ts, tsconfig.json
=> Feat store

README.md, example/router/index.html, example/router/package.json, example/router/pnpm-lock.yaml, example/router/src/App.vue, example/router/src/main.ts, example/router/src/router.ts, example/router/src/views/counter.vue, example/router/src/views/index.vue, example/router/vite.config.js, package.json, packages/@extensions/chibi-vue-router/RouterView.ts, packages/@extensions/chibi-vue-router/history.ts, packages/@extensions/chibi-vue-router/index.ts, packages/@extensions/chibi-vue-router/injectionSymbols.ts, packages/@extensions/chibi-vue-router/router.ts, packages/@extensions/chibi-vue-router/types/index.ts, packages/@extensions/chibi-vue-router/useApi.ts, packages/runtime-core/apiCreateApp.ts, packages/runtime-core/componentOptions.ts, packages/runtime-core/index.ts, tsconfig.json
=> Feat router

packages/compiler-core/ast.ts, packages/compiler-core/codegen.ts, packages/compiler-core/compile.ts, packages/compiler-core/index.ts, packages/compiler-core/options.ts, packages/compiler-core/parse.ts, packages/compiler-core/runtimeHelpers.ts, packages/compiler-core/transform.ts, packages/compiler-core/transforms/transformElement.ts, packages/compiler-dom/index.ts, packages/compiler-dom/parserOptions.ts, packages/runtime-core/component.ts, packages/runtime-core/componentOptions.ts, packages/runtime-core/helpers/resolveAssets.ts, packages/runtime-core/index.ts, packages/shared/domTagConfig.ts, packages/shared/makeMap.ts
=> Feat resolve component name

README.md, example/app/pnpm-lock.yaml, example/app/src/App.vue, example/app/src/views/counter.vue, example/app/src/views/todo-list.vue, packages/@extensions/vite-plugin-chibi-vue/main.ts, packages/@extensions/vite-plugin-chibi-vue/script.ts, packages/compiler-core/babelUtils.ts, packages/compiler-core/codegen.ts, packages/compiler-core/compile.ts, packages/compiler-core/options.ts, packages/compiler-core/runtimeHelpers.ts, packages/compiler-core/transform.ts, packages/compiler-core/transforms/transformExpression.ts, packages/compiler-sfc/compileScript.ts, packages/compiler-sfc/compileTemplate.ts, packages/compiler-sfc/parse.ts
=> Feat script setup

packages/runtime-core/component.ts, packages/runtime-core/componentOptions.ts, packages/runtime-core/componentProps.ts, packages/runtime-core/componentPublicInstance.ts, packages/shared/index.ts, tsconfig.json
=> Feat props

README.md, example/app/src/App.vue, example/app/src/components/SimpleBtn.vue, example/app/src/components/SimpleCard.vue, example/app/src/router.ts, example/app/src/views/emit-test.vue, example/app/src/views/props-test.vue, packages/runtime-core/component.ts, packages/runtime-core/componentEmits.ts, packages/runtime-core/componentOptions.ts
=> Feat emits

example/app/src/App.vue, example/app/src/components/CompilerMacroDemo.vue, example/app/src/router.ts, example/app/src/views/compiler-macro.vue, packages/compiler-core/options.ts, packages/compiler-core/transforms/transformExpression.ts, packages/compiler-sfc/compileScript.ts, packages/shared/index.ts
=> Feat define props

example/app/src/components/CompilerMacroDemo.vue, example/app/src/views/compiler-macro.vue, packages/compiler-sfc/compileScript.ts
=> faet: defineEmits

.github/workflows/deploy.yml, .vscode/settings.json, README.md, book/online-book/.vitepress/config.mts, package.json
=> other: #81 🔹 deploy workflow

book/online-book/.vitepress/config.mts
=> other: #99 🔹 setting ogp

README.md, package.json, tools/vue-playground/main.ts, tools/vue-playground/template/.gitignore, tools/vue-playground/template/README.md, tools/vue-playground/template/index.html, tools/vue-playground/template/package.json, tools/vue-playground/template/pnpm-lock.yaml, tools/vue-playground/template/src/App.vue, tools/vue-playground/template/src/main.ts, tools/vue-playground/template/src/vite-env.d.ts, tools/vue-playground/template/tsconfig.json, tools/vue-playground/template/tsconfig.node.json, tools/vue-playground/template/vite.config.ts
=> other: #104 🔹 create vue playground

.vscode/settings.json, README.md, book/online-book/.vitepress/cache/deps/_metadata.json, book/online-book/src/00-introduction/040-setup-project.md, book/online-book/src/10-minimum-example/090-minimum-sfc.md, book/online-book/src/__wip/020-transform-expression.md, book/online-book/src/en/00-introduction/040-setup-project.md
=> 118 use ni as package manager

README.md, book/online-book/.vitepress/config.mts, book/online-book/src/en/index.md, book/online-book/src/index.md
=> other: #115 🔹 copy

book/online-book/.vitepress/config/en.ts, book/online-book/.vitepress/config/ja.ts, book/online-book/src/bonus/hyper-ultimate-super-extreme-minimal-vue/15-min-impl.md, book/online-book/src/bonus/hyper-ultimate-super-extreme-minimal-vue/index.md, book/online-book/src/en/bonus/hyper-ultimate-super-extreme-minimal-vue/15-min-impl.md, book/online-book/src/en/bonus/hyper-ultimate-super-extreme-minimal-vue/index.md
=> chapter: #128 📜 husem vue

example/vapor/src/MyComponent.vapor.ts, packages/runtime-core/apiInject.ts, packages/runtime-core/apiLifecycle.ts, packages/runtime-core/component.ts, packages/runtime-core/helpers/resolveAssets.ts, packages/runtime-core/index.ts, packages/runtime-core/renderer.ts, packages/vapor/component.ts, packages/vapor/index.ts
=> feat: #155 💪 lifecycle hooks for vapor component

example/vapor/src/App.vue, example/vapor/src/Counter.vue, example/vapor/src/MyComponent.vapor.ts, packages/runtime-core/apiInject.ts, packages/runtime-core/component.ts, packages/runtime-core/renderer.ts, packages/vapor/component.ts, packages/vapor/index.ts
Closes #158 
App.vue
```vue
<script>
import { defineComponent, ref, provide } from "chibivue";
import MyVaporComponent from "./MyComponent.vapor";
export default defineComponent({
components: { MyVaporComponent },
setup() {
const count = ref(0);
provide("App.vue count", count);
return { count };
},
});
</script>
<template>
<div>
<button @click="count++">count: {{ count }}</button>
<MyVaporComponent />
</div>
</template>
```
MyComponent.vapor.ts
```ts
import {
type Ref,
effect,
h,
onMounted,
onBeforeMount,
ref,
inject,
} from "chibivue";
import {
type VaporComponent,
template,
setText,
on,
createComponent,
} from "chibivue/vapor";
// @ts-ignore
import Counter from "./Counter.vue";
const t0 = () => template('<div><button id="btn-on-vapor">');
export default ((self) => {
const appVueCount = …
```
=> feat: #158 💪 provide/inject between VaporComponent and Component

book/online-book/src/20-basic-virtual-dom/010-patch-keyed-children.md, book/online-book/src/20-basic-virtual-dom/030-scheduler.md
@Ubugeeei 
fixed some typo and filled in some words
book/online-book/src/20-basic-virtual-dom/010-patch-keyed-children.md
- In line 142,317,I supplemented the word "map", but correct it if I'm wrong.
- You left the function name empty on line 93, but I'm not sure if that was intentional, so I left it as is.
=> fix: 📌 typo and filled in some words

book/online-book/src/10-minimum-example/040-minimum-virtual-dom.md, book/online-book/src/en/10-minimum-example/040-minimum-virtual-dom.md
=> fix: #174 📌 patch function signature (minimum example)

packages/compiler-core/codegen.ts, packages/compiler-core/options.ts, packages/compiler-core/transforms/vIf.ts, packages/compiler-sfc/compileTemplate.ts, packages/index.ts
=> feat: #176 💪 SharedTransformCodegenOptions

book/online-book/src/10-minimum-example/020-simple-h-function.md, book/online-book/src/en/10-minimum-example/020-simple-h-function.md
Thank you for this wonderful project. I am enjoying it immensely.
In working on the chibivue book, I found a mistake in the file path in the code snippet and have corrected it.
=> Fix the file path in the code snippet 

.github/workflows/deploy.yml
=> other: #189 🔹 notify deployment

packages/compiler-core/src/babelUtils.ts
=> other: #192 🔹 restore getImportedName

.github/workflows/check.yml, examples/vapor/src/MyComponent.vapor.ts, examples/vue/src/main.ts, tsconfig.json
=> 190 ci check build

.github/workflows/check.yml
=> fix: #199 📌 remove pages setup on check workflow

book/impls/10_minimum_example/060_template_compiler2/examples/playground/src/main.ts, book/impls/10_minimum_example/060_template_compiler3/examples/playground/src/main.ts, book/impls/10_minimum_example/070_sfc_compiler/examples/playground/src/main.ts, book/impls/10_minimum_example/070_sfc_compiler2/examples/playground/src/App.vue, book/impls/10_minimum_example/070_sfc_compiler3/examples/playground/src/App.vue, book/impls/10_minimum_example/070_sfc_compiler4/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/010_ref/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/020_shallow_ref/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/030_to_ref/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/040_to_refs/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/050_computed/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/060_computed_setter/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/070_watch/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/080_watch_api_extends/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/090_watch_effect/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/100_reactive_proxy_target_type/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/110_template_refs/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/120_proxy_handler_improvement/examples/playground/src/App.vue, book/online-book/src/10-minimum-example/070-more-complex-parser.md, book/online-book/src/10-minimum-example/080-template-binding.md, book/online-book/src/10-minimum-example/090-minimum-sfc.md, book/online-book/src/10-minimum-example/100-break.md, book/online-book/src/en/00-introduction/010-about.md, book/online-book/src/en/10-minimum-example/070-more-complex-parser.md, book/online-book/src/en/10-minimum-example/080-template-binding.md, book/online-book/src/en/10-minimum-example/090-minimum-sfc.md, book/online-book/src/en/10-minimum-example/100-break.md
=> tweak: #212 🔧 img alt attr

book/impls/10_minimum_example/060_template_compiler3/examples/playground/src/main.ts, book/impls/10_minimum_example/070_sfc_compiler/examples/playground/src/main.ts, book/impls/10_minimum_example/070_sfc_compiler2/examples/playground/src/App.vue, book/impls/10_minimum_example/070_sfc_compiler3/examples/playground/src/App.vue, book/impls/10_minimum_example/070_sfc_compiler4/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/010_ref/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/020_shallow_ref/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/030_to_ref/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/040_to_refs/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/050_computed/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/060_computed_setter/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/070_watch/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/080_watch_api_extends/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/090_watch_effect/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/100_reactive_proxy_target_type/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/110_template_refs/examples/playground/src/App.vue, book/impls/30_basic_reactivity_system/120_proxy_handler_improvement/examples/playground/src/App.vue, book/impls/50_basic_template_compiler/027_event_modifier2/examples/playground/src/main.ts, book/online-book/src/00-introduction/010-about.md, book/online-book/src/10-minimum-example/080-template-binding.md, book/online-book/src/10-minimum-example/090-minimum-sfc.md, book/online-book/src/10-minimum-example/100-break.md, book/online-book/src/50-basic-template-compiler/027-event-modifier.md, book/online-book/src/en/00-introduction/010-about.md, book/online-book/src/en/10-minimum-example/080-template-binding.md, book/online-book/src/en/10-minimum-example/090-minimum-sfc.md, book/online-book/src/en/10-minimum-example/100-break.md, book/online-book/src/en/50-basic-template-compiler/027-event-modifier.md, examples/app/src/views/directive.vue, examples/app/src/views/todo-list.vue
=> other: #212 🔹 add input label

book/impls/10_minimum_example/020_simple_h_function/packages/runtime-core/renderer.ts, book/impls/10_minimum_example/030_reactive_system/packages/runtime-core/renderer.ts, book/online-book/src/10-minimum-example/020-simple-h-function.md, book/online-book/src/en/10-minimum-example/020-simple-h-function.md, pnpm-lock.yaml
https://github.com/Ubugeeei/chibivue/issues/224
=> style: #224 ✨ Change the variable in JavaScript's for...of from 'let'

book/online-book/.vitepress/config/en.ts, book/online-book/.vitepress/config/ja.ts, book/online-book/src/bonus/debug-vuejs-core.md, book/online-book/src/en/bonus/debug-vuejs-core.md
=> dx: #223 vuejs core hmr playground (explain on book)

.textlintrc.json, .vscode/settings.json, package.json, pnpm-lock.yaml
=> pkg: #228 📦 configure textlint (space-between-half-and-full-width)

book/online-book/src/10-minimum-example/030-minimum-reactive.md
@Ubugeeei 
fixed proxy example error!
=> Fixed error by adding missing handler argument to Proxy

book/online-book/src/bonus/hyper-ultimate-super-extreme-minimal-vue/15-min-impl.md
There are several typographical errors on the Japanese page of the appendix, so I corrected them.
refs: https://ubugeeei.github.io/chibivue/bonus/hyper-ultimate-super-extreme-minimal-vue/15-min-impl.html
=> fix: 📌 Corrected typos on the Japanese page of the appendix

book/online-book/src/10-minimum-example/080-template-binding.md, book/online-book/src/10-minimum-example/090-minimum-sfc.md, book/online-book/src/en/10-minimum-example/080-template-binding.md, book/online-book/src/en/10-minimum-example/090-minimum-sfc.md
Hi, @Ubugeeei, Thank you for this wonderful project!
It's so trivial but I fixed the incorrect document expressions.
=> docs: correct some mistakes in the document

book/online-book/src/10-minimum-example/040-minimum-virtual-dom.md, book/online-book/src/10-minimum-example/050-minimum-component.md, book/online-book/src/en/10-minimum-example/040-minimum-virtual-dom.md, book/online-book/src/en/10-minimum-example/050-minimum-component.md
@Ubugeeei 
I fixed the document because found missing link and code😀
=> fix docs link and code

pnpm-lock.yaml, tools/chibivue-playground/main.ts, tools/chibivue-playground/template/package.json
=> fix: dev setup #246

book/impls/10_minimum_example/060_template_compiler/tests/e2e.spec.ts
I saw your post in the [Discord comment](https://discord.com/channels/1190269119426215976/1190279875823673484/1203697627015807026
), so I wrote a chapter that was easy to test 🙂.
If the policy seems right, I'll try to get a few PRs out!
related: https://github.com/Ubugeeei/chibivue/issues/255
=> test: #255 10_minimum_example/060_template_compiler

book/online-book/src/30-basic-reactivity-system/010-ref-api.md
=> fix: 📌 typo

book/online-book/src/10-minimum-example/070-more-complex-parser.md
line 192: paseElement => parseElement
=> fix: Spelling mistake

book/online-book/src/00-introduction/040-setup-project.md
Thanks for looking my PR. 
I found typo in 00-introduction/040-setup-project.md.
fixed typo is:
`tsconfig.js` => `tsconfig.json`
=> fix: typo in 00-introduction/040-setup-project.md

pnpm-lock.yaml
Reverts chibivue-land/chibivue#305
=> Revert "chore(deps): update dependency lint-staged to v15.2.10 - autoclosed"

pnpm-lock.yaml
Reverts chibivue-land/chibivue#304
=> Revert "chore(deps): update dependency citty to v0.1.6"

book/online-book/src/00-introduction/010-about.md, book/online-book/src/ja/00-introduction/010-about.md
=> update: author profile

book/online-book/src/10-minimum-example/030-prerequisite-knowledge-for-the-reactivity-system.md
[docs link](https://book.chibivue.land/10-minimum-example/030-prerequisite-knowledge-for-the-reactivity-system.html)
=> docs: extra-word

book/online-book/.vitepress/config/ja.ts
=> fix: scheduler link
