book/online-book/src/10-minimum-example/010-create-app-api.md

Fixed a minor typo found in the chapter in First Rendering and createApp API.
> runtime-core ではそういった処理書かず、あくまで純粋は TypeScript の世界の中で
> https://ubugeeei.github.io/chibivue/10-minimum-example/010-create-app-api.html#vue-js-%E3%81%AE%E8%A8%AD%E8%A8%88
> renderer.ts に実装した RendererOptions というい interface です。
> https://ubugeeei.github.io/chibivue/10-minimum-example/010-create-app-api.html#di-%E3%81%A8-dip

Fixed typo in First Rendering and createApp API.

---

book/online-book/src/00-introduction/040-setup-project.md
book/online-book/src/en/00-introduction/040-setup-project.md

During the execution of the steps in the playground setup section of the book, the command `nlx create vite`, the following error occurred:
> プレイグラウンド側の構築
> ```sh
> nlx create vite
> ```
> https://ubugeeei.github.io/chibivue/00-introduction/040-setup-project.html#%E3%83%95%E3%82%9A%E3%83%AC%E3%82%A4%E3%82%AF%E3%82%99%E3%83%A9%E3%82%A6%E3%83%B3%E3%83%88%E3%82%99%E5%81%B4%E3%81%AE%E6%A7%8B%E7%AF%89
```sh
$ nlx create vite
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
 ERR_PNPM_DLX_NO_BIN  No binaries found in create
```
This is probably due to the fact that `ni` does not support the `npm create` equivalent.
`npm init(create)` is a `npx` wapper supported by `ni`, so I changed it to run with `nlx create-vite`.
> The init command is transformed to a corresponding …

Fixed command to create a vite project for playground.

---

book/online-book/src/10-minimum-example/020-simple-h-function.md

I fixed the incorrect inline code syntax highlighting in accordance with the English document.
> それでは、render 関数を実装してみましょう。 RendererOptions に createElementとcreateTextとinsert` を実装します。
> https://ubugeeei.github.io/chibivue/10-minimum-example/020-simple-h-function.html#h-function-%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B
> Now, let's implement the render function. Implement createElement, createText, and insert in RendererOptions.
> https://ubugeeei.github.io/chibivue/en/10-minimum-example/020-simple-h-function.html#implementing-the-h-function

fixed inline code syntax highlighting.

---

book/online-book/src/00-introduction/040-setup-project.md
book/online-book/src/en/00-introduction/040-setup-project.md

The following playground setup procedure uses the default `tsconfig.json` of `nlx create-vite` as is.
https://ubugeeei.github.io/chibivue/00-introduction/040-setup-project.html#プレイグラウンド側の構築
However, the default `tsconfig.json` does not recognize `chibivue` as an alias, as shown below,
```sh
mkdir examples
cd examples
nlx create-vite
cat examples/playground/tsconfig.json
{
"compilerOptions": {
"target": "ES2020", { "compilerOptions": { "compilerOptions": { "compilerOptions".
"skipLibCheck": true,.
/* Bundler mode */
"moduleResolution": "bundler", /* Bundler mode */.
"resolveJsonModule": true, /* Bundler mode */ "moduleResolution": "bundler", "allowImportingTsExtensions": true, "resolveJsonModule": true, "resolveJsonModule": true
"isolatedModules": true, "noEmit": true, "noEmit": true, …
```

Add step for modifying tsconfig.json to Setup Project.

---

book/online-book/src/10-minimum-example/040-minimum-virtual-dom.md

Fixed typo in comment for code block diff for minimum virtual DOM.
> ```ts
> export interface VNode<HostNode = RendererNode> {
>  type: VNodeTypes;
>  props: VNodeProps | null;
>  children: VNodeNormalizedChildren;
>  el: HostNode | undefined; // [!code++]
> }
> ```
> https://ubugeeei.github.io/chibivue/10-minimum-example/040-minimum-virtual-dom.html#%E5%AE%9F%E9%9A%9B%E3%81%AB%E5%AE%9F%E8%A3%85%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B
> Colored Diffs in Code Blocks
> Adding the `// [!code --]` or `// [!code ++]` comments on a line will create a diff of that line, while keeping the colors of the codeblock.
> https://vitepress.dev/guide/markdown#colored-diffs-in-code-blocks

fixed typo for enabled colored diffs in code blocks.

---

book/impls/10_minimum_example/040_vdom_system/packages/runtime-core/renderer.ts
book/online-book/src/10-minimum-example/040-minimum-virtual-dom.md
book/online-book/src/en/10-minimum-example/040-minimum-virtual-dom.md

When type checking is performed on the `10_minimum_example/040_vdom_system` sample code, the following error occurs.
```ts
$ pnpm tsc --noEmit --project book/impls/10_minimum_example/040_vdom_system/examples/playground/tsconfig.json
book/impls/10_minimum_example/040_vdom_system/packages/runtime-core/renderer.ts:129:9 - error TS6133: 'n2' is declared but its value is never read.
129     let n2: VNode = null!
~~
Found 1 error in book/impls/10_minimum_example/040_vdom_system/packages/runtime-core/renderer.ts:129
```
Therefore, unnecessary variable removed.

fix: 📌 Fixed TypeScript errors by removing unnecessary variable.

---

book/impls/10_minimum_example/060_template_compiler2/packages/compiler-core/parse.ts
book/impls/10_minimum_example/060_template_compiler3/packages/compiler-core/parse.ts
book/impls/10_minimum_example/060_template_compiler3/packages/runtime-core/componentOptions.ts
book/impls/10_minimum_example/070_sfc_compiler/packages/compiler-core/parse.ts
book/impls/10_minimum_example/070_sfc_compiler/packages/runtime-core/componentOptions.ts
book/impls/10_minimum_example/070_sfc_compiler2/packages/compiler-core/parse.ts
book/impls/10_minimum_example/070_sfc_compiler2/packages/runtime-core/componentOptions.ts
book/impls/10_minimum_example/070_sfc_compiler3/packages/compiler-core/parse.ts
book/impls/10_minimum_example/070_sfc_compiler3/packages/runtime-core/componentOptions.ts
book/impls/10_minimum_example/070_sfc_compiler4/packages/compiler-core/parse.ts
book/impls/10_minimum_example/070_sfc_compiler4/packages/runtime-core/componentOptions.ts
book/online-book/src/10-minimum-example/070-more-complex-parser.md
book/online-book/src/en/10-minimum-example/070-more-complex-parser.md

There is an unused code in Minimum Example sample code,
The following type check error occurs, so I removed it from the sample code and the documentation.
```sh
... /... /packages/compiler-core/parse.ts:201:9 - error TS6133: 'parent' is declared but its value is never read.
201 const parent = last(ancestors)
~~~~~~
```
```sh
../../packages/runtime-core/componentOptions.ts:1:1 - error TS6133: 'Data' is declared but its value is never read.
1 import { Data } from './component'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

fix: 📌 Remove unused code in Minimum Example sample code

---

book/online-book/src/en/10-minimum-example/040-minimum-virtual-dom.md

> ```ts
> export interface VNode<HostNode = RendererNode> {
>  type: VNodeTypes;
>  props: VNodeProps | null;
>  children: VNodeNormalizedChildren;
>  el: HostNode | undefined; // [!code++]
> }
> ```
> https://ubugeeei.github.io/chibivue/en/10-minimum-example/040-minimum-virtual-dom.html#actual-implementation
> Colored Diffs in Code Blocks
> Adding the `// [!code --]` or `// [!code ++]` comments on a line will create a diff of that line, while keeping the colors of the codeblock.
> https://vitepress.dev/guide/markdown#colored-diffs-in-code-blocks
related PR
* https://github.com/Ubugeeei/chibivue/pull/219
There was an omission in the above correction 😭

tweak: 🔧 Fixed typo in comment in code block diff for English version of minimum virtual DOM.

---

book/impls/10_minimum_example/060_template_compiler2/packages/compiler-core/compile.ts

There is an unused `generate` in the sample code `packages/compiler-core/compile.ts` in the Minimum Example, The following type check error occurs, so I removed it from the sample code.
```sh
../../packages/compiler-core/compile.ts:1:1 - error TS6133: 'generate' is declared but its value is never read.
1 import { generate } from './codegen'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in ../../packages/compiler-core/compile.ts:1
```

fix: 📌 Remove unused `generate` in Minimum Example

---

book/impls/10_minimum_example/070_sfc_compiler/plugin-sample/src/main.ts
book/impls/10_minimum_example/070_sfc_compiler2/examples/playground/src/main.ts
book/impls/10_minimum_example/070_sfc_compiler3/examples/playground/src/main.ts
book/impls/10_minimum_example/070_sfc_compiler4/examples/playground/src/main.ts

fixed https://github.com/Ubugeeei/chibivue/issues/233
As shown below, a type error TS2307 occurs when importing `App.vue` in the sample code.
```sh
$ pnpm tsc --noEmit --project book/impls/10_minimum_example/070_sfc_compiler/plugin-sample/tsconfig.json
book/impls/10_minimum_example/070_sfc_compiler/plugin-sample/src/main.ts:3:17 - error TS2307: Cannot find module './App.vue' or its corresponding type declarations.
3 import App from './App.vue'
~~~~~~~~~~~
Found 1 error in book/impls/10_minimum_example/070_sfc_compiler/plugin-sample/src/main.ts:3
```
`App.vue` is written in javascript and has no type definitions, so `@ts-ignore` is added to ignore type checking.

fix: 📌 Fixed a type error on import of `App.vue` in sample code.

---

.github/workflows/check.yml
.github/workflows/deploy.yml

test: #238 ✏️ check fmt and lint on actions

---

book/online-book/.vitepress/theme/main.css

resolve #244 
The colors of `--c-teal` and `--c-teal-light` have been adjusted and adopted as the link button colors.
| dark mode | light mode |
|-------------|--------------|
| ![Screenshot of the hero image section of the chibivue TOP page (in dark mode)](https://github.com/Ubugeeei/chibivue/assets/1996642/99eb67d7-e30c-414e-8b1e-4adfc6205f41) | ![Screenshot of the hero image section of the chibivue TOP page (in light mode)](https://github.com/Ubugeeei/chibivue/assets/1996642/c0a3a872-15c1-4fb9-9996-2722e4e3a2c7) |
Each of the link button colors also meets the `4.5:1` color contrast ratio required by WCAG [^1].
[^1]: [Understanding Success Criterion 1.4.3: Contrast (Minimum) | WAI | W3C](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)
| Default, Active Color | Hover …

update: contrast ratio of VPButton colors on the top page to meet the WCAG standards

---

book/impls/00_introduction/010_project_setup/tests/index.spec.ts
book/impls/10_minimum_example/010_create_app/tests/e2e.spec.ts
book/impls/10_minimum_example/010_create_app2/tests/e2e.spec.ts
book/impls/10_minimum_example/020_simple_h_function/tests/e2e.spec.ts
book/impls/10_minimum_example/030_reactive_system/tests/e2e.spec.ts
book/impls/10_minimum_example/040_vdom_system/tests/e2e.spec.ts
book/impls/10_minimum_example/050_component_system/tests/e2e.spec.ts
book/impls/10_minimum_example/050_component_system2/tests/e2e.spec.ts
book/impls/10_minimum_example/050_component_system3/tests/e2e.spec.ts
package.json
pnpm-lock.yaml
tsconfig.json
vitest.config.ts

test: #66 ✏️ chapter's e2e tests (~ 10_minimum_example/050_component_system3)

---

book/impls/10_minimum_example/060_template_compiler2/packages/compiler-core/codegen.ts
book/impls/10_minimum_example/060_template_compiler2/packages/compiler-core/compile.ts

[changes]  
Reflects changes in chapter  ”[Generating the render function based on the AST](https://ubugeeei.github.io/chibivue/en/10-minimum-example/070-more-complex-parser.html#generating-the-render-function-based-on-the-ast)”.
Currently, the code is at chapter "[After finishing the implementation of the parser](https://ubugeeei.github.io/chibivue/en/10-minimum-example/070-more-complex-parser.html#after-finishing-the-implementation-of-the-parser)"
| before | After |
| ------ | ----- |
| ![image](https://github.com/Ubugeeei/chibivue/assets/47783146/9f90ab16-4c03-401b-8664-e029eead2c3d) | ![image](https://github.com/Ubugeeei/chibivue/assets/47783146/b396fecb-4f5a-4fb6-8409-706c7db4a194) |
[background]
I was going to write a test for "10_minimum_example/060_template_compiler2" but noticed …

update:Change screen state to  "Generate render function based on AST"

---

book/online-book/src/10-minimum-example/070-more-complex-parser.md

Fixed a minor typo and tweaked wording found in the chapter in more complex HTML.
> まずはシンプルな parseText の方から.一部、parseText 以外でも使うユーティリティも実装しているので少しだけ長いです。
> https://ubugeeei.github.io/chibivue/10-minimum-example/070-more-complex-parser.html#parsetext

fix: 📌 Fixed typo and tweaked wording in more complex HTML.

---

book/online-book/src/10-minimum-example/070-more-complex-parser.md
book/online-book/src/en/10-minimum-example/070-more-complex-parser.md

There is a place where `advanceSpaces` is called in the implementation of `parseTag`, but since the implementation of `advanceSpaces` did not exist in the document, I added the implementation of `advanceSpaces` to the utilities in the sample code of the `parseText` implementation.
```ts
function parseTag(context: ParserContext, type: TagType): ElementNode {
// Tag open.
const start = getCursor(context)
const match = /^<\/?([a-z][^\t\r\n\f />]*)/i.exec(context.source)!
const tag = match[1]
advanceBy(context, match[0].length)
advanceSpaces(context)
```
ref: https://ubugeeei.github.io/chibivue/10-minimum-example/070-more-complex-parser.html#parseelement
I referred to the following description for the implementation of advanceSpaces. …

fix: 📌 Added the implementation of advanceSpaces to the sample code in the document.

---

package.json
pnpm-lock.yaml

Resolves #271
**Changes**
- Update Vitepress to latest version
- Added `^` to version since the package is now stable
- Should we use fixed version?
- Check all the pages and styles doesn't look affected in a bad way
- Charts rendered by `vitepress-plugin-mermaid` also looks fine.
- Vitepress team changed default theme so look-and-feel is changed (e.g. coloring)
- Should we keep color scheme?
---
| As-Is | To-Be |
|--------|--------|
| <img src="https://github.com/Ubugeeei/chibivue/assets/16436160/80eda4cf-f304-439b-84e3-d5d6cb7f9118"> | <img src="https://github.com/Ubugeeei/chibivue/assets/16436160/0528216b-e3fb-42ad-a29f-0fccc5270ee2"> |
| <img src="https://github.com/Ubugeeei/chibivue/assets/16436160/7fc066b7-1a52-4690-8e9b-848cff3cbd2f"> | <img …

chore: update vitepress

---

book/online-book/src/10-minimum-example/090-minimum-sfc.md

Fixed a minor typo in the chapter in Minimum SFC.
> つまりは、元々のコードの export 文から良い感じに export 対象をを抜き出し、_sfc_main という変数に代入できるようになればゴールということです。
> https://ubugeeei.github.io/chibivue/10-minimum-example/090-minimum-sfc.html#script-%E3%81%AE-default-export-%E3%82%92%E6%9B%B8%E3%81%8D%E6%8F%9B%E3%81%88%E3%82%8B
> 子の仕組みを使って SFC の style ブロックを仮想の css ファイルとして読み込むようにしてみます。
> https://ubugeeei.github.io/chibivue/10-minimum-example/090-minimum-sfc.html#%E4%BB%AE%E6%83%B3%E3%83%A2%E3%82%B7%E3%82%99%E3%83%A5%E3%83%BC%E3%83%AB
> もちろんエラーになります。やったね( ？　)
> https://ubugeeei.github.io/chibivue/10-minimum-example/090-minimum-sfc.html#%E6%BA%96%E5%82%99
I have confirmed that the check action was successful.
https://github.com/madogiwa0124/chibivue/actions/runs/8917017380/job/24489410952

fix: 📌 Fixed typo in Minimum SFC.

---

book/online-book/src/10-minimum-example/090-minimum-sfc.md
book/online-book/src/en/10-minimum-example/090-minimum-sfc.md

I have made the following fix to the Minimal SFC chapter.
Fixed it to use commands with `ni`.
> nlx - download & execute
> https://github.com/antfu-collective/ni?tab=readme-ov-file#nlx---download--execute
And, added steps to install vite before creating a vite plugin
because `import type { Plugin } from 'vite'` will cause an error if vite is not installed.
> `~/packages/@extensions/vite-plugin-chibivue/index.ts`
>
> ```ts
> import type { Plugin } from 'vite'
> ```
>
> https://ubugeeei.github.io/chibivue/10-minimum-example/090-minimum-sfc.html#%E6%BA%96%E5%82%99
I have confirmed that the check action was successful.
https://github.com/madogiwa0124/chibivue/actions/runs/8917514928

fix: 📌 Fixed command in Minimum SFC.

---

book/online-book/src/10-minimum-example/090-minimum-sfc.md
book/online-book/src/en/10-minimum-example/090-minimum-sfc.md

In the step for adding `option` to `generate`, it seemed necessary to add `option` to the arguments of `genNode` and `genElement` as well.
https://github.com/Ubugeeei/chibivue/blob/v0.0.8/book/impls/10_minimum_example/070_sfc_compiler3/packages/compiler-core/codegen.ts
Therefore, `genNode` and `genElement` with added arguments were also added to the sample code.
> 一時的な対応なのであまり厳格ではないのですが、概ね動作するようになると思います。
>
> ```ts
> export const generate = (
>   {
>     children,
>   }: {
>     children: TemplateChildNode[]
>   },
>   option: Required<CompilerOptions>,
> ): string => {
>   // isBrowser が false の場合は with 文を含まないコードを生成する
>   return `${option.isBrowser ? 'return ' : ''}function render(_ctx) {
>     ${option.isBrowser ? 'with (_ctx) {' : ''}
>       const { h } = ChibiVue;
>       return …
```

fix: 📌 Fixed sample code in Minimum SFC.

---

book/online-book/src/10-minimum-example/030-minimum-reactive.md

I found Japanese typo in Section 3 Minimum Reactive of Minimum Example.
I deleted duplicated「を」.
https://ubugeeei.github.io/chibivue/10-minimum-example/030-minimum-reactive.html

fix: typo in 10-minimum-example/030-minimum-reactive.md

---

book/online-book/src/10-minimum-example/060-minimum-template-compiler.md
book/online-book/src/en/10-minimum-example/060-minimum-template-compiler.md

I have fixed the incorrect directory paths in "060-minimum-template-compiler.md".
I changed `~/packages/src` to `~/packages` in the following quoted text.
>アプローチが理解できたら早速実装してみましょう．`~/packages/src` に`compiler-core`というディレクトリを作ってそこに`index.ts`, `parse.ts`, `codegen.ts`を作成します．
>
>```sh
>pwd # ~/
>mkdir packages/compiler-core
>touch packages/compiler-core/index.ts

fix: 📌 fix file path in 060-minimum-template-compiler.md

---

book/online-book/src/ja/00-introduction/040-setup-project.md

I found a typo in 040 of Japanese.
I fixed it considering the English version as correct

fix: use consitent vite.config.js extension in book

---

book/online-book/src/ja/00-introduction/040-setup-project.md

While following the steps in the guide, I was faced with an error as shown in the screenshot. it appears that the contents of tsconfig.json need to be updated, so I am submitting this PR.

docs: Add "ES2020" to compilerOptions.lib in tsconfig.json
